### ISSUE TITLE
Error when upgrade to v1.2.0

### ISSUE THREAD

**Issue by vuxuanlai** [mr-karan/calert#15]
I deployed calert by helm and got the error when use v1.2.0 as below:

> ERR: 2020/05/16 14:03:25 /home/karan/Projects/calert/main.go:90: Error reading config: Config File "config" Not Found in "[/]"

**Comment by MPV** [comment]
@vuxuanlai What command (and values) did you use when installing?

**Comment by MPV** [comment]
It works for me, for example when I do this:

```bash
$ helm install calert ./helm/
NAME: calert
LAST DEPLOYED: Tue May 19 16:41:02 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=calert,app.kubernetes.io/instance=calert" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:6000 to use your application"
  kubectl port-forward $POD_NAME 6000:6000
```
```bash
$ kubectl get all
NAME                          READY   STATUS              RESTARTS   AGE
pod/calert-6c7d95c59f-kh6gn   0/1     ContainerCreating   0          8s

NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/calert       ClusterIP   10.99.253.206   <none>        6000/TCP   8s
service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP    4m40s

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/calert   0/1     1            0           8s

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/calert-6c7d95c59f   1         1         0       8s
```
```
$ kubectl logs -l app.kubernetes.io/name=calert
SYS: 2020/05/19 14:49:27 /calert/main.go:133: listening on :6000 | /tmp/calert.sock
```

**Comment by vuxuanlai** [comment]
I pull your repo to my local, and then edit values.yaml in helm folder. I changed tag to v1.2.0 as below:

> image:
>   repository: mrkaran/calert
>   tag: v1.2.0
>   pullPolicy: Always

and then apply with the command: 

> helm install calert ./helm/

I got the error as my question.

**Comment by vuxuanlai** [comment]
I think you need to check you [https://github.com/mr-karan/calert/blob/master/Dockerfile](url)

**Comment by MPV** [comment]
@mr-karan I ran into these same problems now when trying out the `v1.2.0` docker image tag.

Before, the arguments were:
[`"--config.file", "/etc/calert/config.toml"`](https://github.com/mr-karan/calert/blob/19e30bd1c7c6773ef538ad866ad13322d45b409b/docker/Dockerfile#L16)

Now they are:
[`"--config", "/etc/calert/config.toml"`](https://github.com/mr-karan/calert/blob/master/Dockerfile#L6)

Note `config.file` vs `config`.

If I run the docker image locally and compare those arguments, I see the new arguments don't work:

```bash
$ docker run --rm -it --name calert mrkaran/calert:v1.2.0 \
    ./calert --config /etc/calert/config.toml
ERR: 2020/05/20 09:26:38 /home/karan/Projects/calert/main.go:90: Error reading config: Config File "config" Not Found in "[/]"
```
```bash
$ docker run --rm -it --name calert mrkaran/calert:v1.2.0 \
    ./calert --config.file /etc/calert/config.toml
SYS: 2020/05/20 09:26:49 /home/karan/Projects/calert/main.go:134: listening on :6000 | /tmp/calert.sock
^C%
```

The helm chart (that @vuxuanlai and I are using) doesn't support overriding the command (so we don't have a workaround), but maybe it's better if we patch the [Dockerfile](https://github.com/mr-karan/calert/blob/master/Dockerfile#L6)?

**Comment by mr-karan** [comment]
Oh shoot. Yes this is my bad. Do you wanna send a patch?

**Comment by MPV** [comment]
Yup, see #19.

How's your availability for releasing a `v1.3.0` with this?

**Comment by MPV** [comment]
I added #20 also, for giving myself (and maybe @vuxuanlai too) a workaround until #19 is merged and a new docker image has been published.

**Comment by mr-karan** [comment]
This should be fixed with https://github.com/mr-karan/calert/releases/tag/v1.2.1
