### PR TITLE
Dockerfile: fix config.file argument

### LINKED ISSUE #15: Error when upgrade to v1.2.0
I deployed calert by helm and got the error when use v1.2.0 as below:

> ERR: 2020/05/16 14:03:25 /home/karan/Projects/calert/main.go:90: Error reading config: Config File "config" Not Found in "[/]"

### PR DESCRIPTION
**Pull request by MPV**
I hope this fixes #15.

### CODE REVIEW

**Comment by MPV** [comment]
@mr-karan 😊

**Comment by mr-karan** [comment]
https://github.com/mr-karan/calert/releases/tag/v1.2.1 Released
